Support `rediss`-schema
voiio/Sam pull request #129
Opened 2024-10-07 11:50 UTC by amureki

2024-10-07 12:12 UTC, codingjoe reviewed
That URL scheme is natively supported https://github.com/redis/redis-py/blob/2e46613dcdf9db7f948f3258fee1c9199da8cbfa/redis/connection.py#L1163

2024-10-07 12:17 UTC, amureki commented
@codingjoe you are right, but I did not finish working on this PR and did not elaborate properly (thus wrong description/title).

I am referring to the way Heroku (and a couple of other providers) work with `rediss` schema:

They do require disabling the certificate validation - https://devcenter.heroku.com/articles/connecting-heroku-redis

2024-10-07 21:06 UTC, codingjoe requested changes
Please use redis' native `parse_url` function and override the single parameter. I would also suggest injecting the value of the parameter via an environment variable, since this is a Heroku problem.

2024-10-08 08:48 UTC, amureki commented
> Please use redis' native `parse_url` function and override the single parameter. I would also suggest injecting the value of the parameter via an environment variable, since this is a Heroku problem.

Yeah, my initial attempt of doing so failed, as it "magically" uses different connections based on the schema provided.

2024-10-08 09:22 UTC, merged